//Labelling 

//Level 2

label  variable c1  "Centre, Round"
label  variable c2  "FSU Serial No."
label  variable c3  "Round"
label  variable c4  "Schedule"
label  variable c5  "Sample"
label  variable c6  "Sector"
label  variable c7  "NSS-Region"
label  variable c8  "District"
label  variable c9  "Stratum"
label  variable c10  "Sub-stratum"
label  variable c11  "Sub-Round"
label  variable c12  "Sub-sample"
label  variable c13  "FOD-Sub-Region"
label  variable c14  "Hamlet group/ Sub-block no."
label  variable c15  "Second-stage-stratum no."
label  variable c16  "Sample hhld. No."
label  variable q22  "Level"
label  variable q23  "Filler"
label  variable q24  "Household size"
label  variable q24a  "Whether HHD paid major share for childbirth expenses for any non-HHD female member"
label  variable q25  "NIC-2008 five digit code"
label  variable q26  "NCO-2004 three digit code"
label  variable q27  "Household type"
label  variable q28  "Religion"
label  variable q29  "Social group "
label  variable q210  "Type of latrine usually used"
label  variable q210a  "Access to latrine"
label  variable q210b  "How many members use the latrine"
label  variable q212  "Major source of drinking water"
label  variable q212a  "Arrangement of garbage disposal"
label  variable q213  "Primary source of energy for cooking"
label  variable q213a  "Was there sudden outbreak of communicable disease in the community"
label  variable q214  "Amount of medical insurance premium (Rs.)"
label  variable q215  "Household usual consumer expenditure (Rs.)"
label  variable q216  "Blank"
label  variable nss  "NSS"
label  variable nsc  "NSC"
label  variable mlt  "MULT"


//Level 3

label  variable c1  "Centre, Round"
label  variable c2  "FSU Serial No."
label  variable c3  "Round"
label  variable c4  "Schedule"
label  variable c5  "Sample"
label  variable c6  "Sector"
label  variable c7  "NSS-Region"
label  variable c8  "District"
label  variable c9  "Stratum"
label  variable c10  "Sub-stratum"
label  variable c11  "Sub-Round"
label  variable c12  "Sub-sample"
label  variable c13  "FOD-Sub-Region"
label  variable c14  "Hamlet group/ Sub-block no."
label  variable c15  "Second-stage-stratum no."
label  variable c16  "Sample hhld. No."
label  variable q42  "Level"
label  variable q43  "Filler"
label  variable q44  "Person serial no."
label  variable q45  "Relation to head"
label  variable q46  "Gender"
label  variable q47  "Age(in years)"
label  variable q48  "Marital status"
label  variable q49  "General education"
label  variable q410  "Usual principal activity status code"
label  variable q411  "During last 365 days-whether hopitalised "
label  variable q412  "If 1 in col. 9, no. of times hospitalised"
label  variable q411a  "Whether pregnant (female members of age 15 to 49 years)"
label  variable q411b  "Whether paid major share for child-birth expenses"
label  variable q411c  "Whether suffered from any communicable disease"
label  variable q413  "Whether suffering from any chronic ailment"
label  variable q414  "Whether suffered/suffering from any other ailment: any time during last 15 days"
label  variable q415  "Whether suffered/suffering from any other ailment: on the day before date of survey"
label  variable q416  "Whether covered by any scheme for health expenditure support"
label  variable q417  "Reporting of col. 14 to 16"
label  variable q418  "Blank"
label  variable nss  "NSS"
label  variable nsc  "NSC"
label  variable mlt  "MULT"

//Level 4

label  variable c1  "Centre, Round"
label  variable c2  "FSU Serial No."
label  variable c3  "Round"
label  variable c4  "Schedule"
label  variable c5  "Sample"
label  variable c6  "Sector"
label  variable c7  "NSS-Region"
label  variable c8  "District"
label  variable c9  "Stratum"
label  variable c10  "Sub-stratum"
label  variable c11  "Sub-Round"
label  variable c12  "Sub-sample"
label  variable c13  "FOD-Sub-Region"
label  variable c14  "Hamlet group/ Sub-block no."
label  variable c15  "Second-stage-stratum no."
label  variable c16  "Sample hhld. No."
label  variable q32  "Level"
label  variable q33  "Filler"
label  variable q34  "Person serial no."
label  variable q35  "Gender"
label  variable q36  "Age at death"
label  variable q37  "Whether medical attention received before death"
label  variable q38  "Whether hospitalised"
label  variable q39  "If 1 in col. 6, no. of times hospitalised"
label  variable q39a  "Reason for non-hospitalisation just before death"
label  variable q310  "Whether pregnant any time during last 365 days"
label  variable q311  "If 1 in col. 9, time of death"
label  variable q312  "Blank"
label  variable nss  "NSS"
label  variable nsc  "NSC"
label  variable mlt  "MULT"

//Level 5

label  variable c1  "Centre, Round"
label  variable c2  "FSU Serial No."
label  variable c3  "Round"
label  variable c4  "Schedule"
label  variable c5  "Sample"
label  variable c6  "Sector"
label  variable c7  "NSS-Region"
label  variable c8  "District"
label  variable c9  "Stratum"
label  variable c10  "Sub-stratum"
label  variable c11  "Sub-Round"
label  variable c12  "Sub-sample"
label  variable c13  "FOD-Sub-Region"
label  variable c14  "Hamlet group/ Sub-block no."
label  variable c15  "Second-stage-stratum no."
label  variable c16  "Sample hhld. No."
label  variable q52  "Level"
label  variable q53  "Filler"
label  variable q54  "Srl. no. of hospitalisation case"
label  variable q55  "Srl. no. of member hospitalised (as in col. 1, bl. 4A & 4B/ 5)"
label  variable q56  "Age (as in col. 5, bl. 4A & 4B/ col. 4, bl.5)"
label  variable q57  "Nature of ailment"
label  variable q58  "Nature of treatment"
label  variable q59  "Type of medical institution"
label  variable q59a  "Reason for not availing govt./public hospital"
label  variable q510  "Type of ward"
label  variable q511  "When admitted"
label  variable q512  "When discharged"
label  variable q513  "Duration of stay in hospital (days)"
label  variable q514  "Surgery"
label  variable q515  "Medicine"
label  variable q516  "X-ray/ ECG/ EEG/ Scan"
label  variable q517  "Other diagnostic tests"
label  variable q518  "Treated before hospitalisation"
label  variable q519  "If 1 in item 15, nature of treatment"
label  variable q520  "If 1 in item 15, level of care"
label  variable q521  "If 1 in item 15, duration of treatment (days)"
label  variable q522  "Treatment continued after discharge?"
label  variable q523  "If 1 in item 19, nature of treatment"
label  variable q524  "If 1 in item 19, level of care"
label  variable q525  "If 1 in item 19, duration of treatment (days)"
label  variable q526  "Blank"
label  variable nss  "NSS"
label  variable nsc  "NSC"
label  variable mlt  "MULT"

//Level 6

label  variable c1  "Centre, Round"
label  variable c2  "FSU Serial No."
label  variable c3  "Round"
label  variable c4  "Schedule"
label  variable c5  "Sample"
label  variable c6  "Sector"
label  variable c7  "NSS-Region"
label  variable c8  "District"
label  variable c9  "Stratum"
label  variable c10  "Sub-stratum"
label  variable c11  "Sub-Round"
label  variable c12  "Sub-sample"
label  variable c13  "FOD-Sub-Region"
label  variable c14  "Hamlet group/ Sub-block no."
label  variable c15  "Second-stage-stratum no."
label  variable c16  "Sample hhld. No."
label  variable q62  "Level"
label  variable q63  "Filler"
label  variable q64  "Srl. no. of hospitalisation case (as in item 1, bl. 6)"
label  variable q65  "Srl. no. of member hospitalised (as in item 2, bl. 6)"
label  variable q66  "Age (as in item 3, bl. 6)"
label  variable q67  "Whether any medical advice provided free"
label  variable q68  "Package component (Rs.)"
label  variable q69  "Doctor's/ surgeon's fee (Rs.)"
label  variable q610  "Medicines (Rs.)"
label  variable q611  "Diagonistic tests (Rs.)"
label  variable q612  "Bed charges (Rs.)"
label  variable q613  "Other medical expenses (Rs.)"
label  variable q614  "Medical expenditure(Rs.):total (items 5 to 10)"
label  variable q615  "Transport for patient (Rs.)"
label  variable q616  "Other non-medical expenses (Rs.)"
label  variable q617  "Expenditure (Rs.): Total (items 11 to 13)"
label  variable q617a  "Blank"
label  variable nss  "NSS"
label  variable nsc  "NSC"
label  variable mlt  "MULT"

//Level 7

label  variable c1  "Centre, Round"
label  variable c2  "FSU Serial No."
label  variable c3  "Round"
label  variable c4  "Schedule"
label  variable c5  "Sample"
label  variable c6  "Sector"
label  variable c7  "NSS-Region"
label  variable c8  "District"
label  variable c9  "Stratum"
label  variable c10  "Sub-stratum"
label  variable c11  "Sub-Round"
label  variable c12  "Sub-sample"
label  variable c13  "FOD-Sub-Region"
label  variable c14  "Hamlet group/ Sub-block no."
label  variable c15  "Second-stage-stratum no."
label  variable c16  "Sample hhld. No."
label  variable q62a  "Level"
label  variable q63a  "Filler"
label  variable q64a  "Srl. no. of hospitalisation case (as in item 1, bl. 6)"
label  variable q65a  "Srl. no. of member hospitalised (as in item 2, bl. 6)"
label  variable q66a  "Age (as in item 3, bl. 6)"
label  variable q618  "Total amount reimbursed by medical insurance (Rs.)"
label  variable q619  "Major source of finance"
label  variable q620  "2nd most important source"
label  variable q621  "Place of hospitalisation (code)"
label  variable q621a  "If code 5 in item 18, state code"
label  variable q622  "Loss of household income, if any, due to hospitalisation (Rs.)"
label  variable q623  "Blank"
label  variable nss  "NSS"
label  variable nsc  "NSC"
label  variable mlt  "MULT"

//Level 8

label  variable c1  "Centre, Round"
label  variable c2  "FSU Serial No."
label  variable c3  "Round"
label  variable c4  "Schedule"
label  variable c5  "Sample"
label  variable c6  "Sector"
label  variable c7  "NSS-Region"
label  variable c8  "District"
label  variable c9  "Stratum"
label  variable c10  "Sub-stratum"
label  variable c11  "Sub-Round"
label  variable c12  "Sub-sample"
label  variable c13  "FOD-Sub-Region"
label  variable c14  "Hamlet group/ Sub-block no."
label  variable c15  "Second-stage-stratum no."
label  variable c16  "Sample hhld. No."
label  variable q72  "Level"
label  variable q73  "Filler"
label  variable q74  "Srl. no. of spell of ailment"
label  variable q75  "Srl. no. of member reporting ailment (as in col. 1, bl. 4A/ 5)"
label  variable q76  "Age (as in col. 5, bl. 4A/ col. 4, bl.5)"
label  variable q77  "No. of days within the ref. period - ill"
label  variable q78  "No. of days within the ref. period - on restricted activity"
label  variable q79  "No. of days within the ref. period - confined to bed"
label  variable q710  "Nature of ailment"
label  variable q711  "Whether chornic"
label  variable q712  "Status of ailment"
label  variable q713  "Total duration of ailment (days)"
label  variable q714  "Nature of treatment"
label  variable q715  "Whether hospitalised"
label  variable q716  "Whether treatment taken on medical advice"
label  variable q717  "Level of care"
label  variable q718  "Reason for not availing Govt. sources"
label  variable q719  "Reason for not seeking medical advice"
label  variable q720  "Whom consulted"
label  variable q722  "Blank"
label  variable nss  "NSS"
label  variable nsc  "NSC"
label  variable mlt  "MULT"

//Level 9

label  variable c1  "Centre, Round"
label  variable c2  "FSU Serial No."
label  variable c3  "Round"
label  variable c4  "Schedule"
label  variable c5  "Sample"
label  variable c6  "Sector"
label  variable c7  "NSS-Region"
label  variable c8  "District"
label  variable c9  "Stratum"
label  variable c10  "Sub-stratum"
label  variable c11  "Sub-Round"
label  variable c12  "Sub-sample"
label  variable c13  "FOD-Sub-Region"
label  variable c14  "Hamlet group/ Sub-block no."
label  variable c15  "Second-stage-stratum no."
label  variable c16  "Sample hhld. No."
label  variable q82  "Level"
label  variable q83  "Filler"
label  variable q84  "Srl. no. of spell of ailment(as in item 1, block 8)"
label  variable q84a  "Srl. no. of member reporting ailment(as in item 2, block 8)"
label  variable q85  "Age (in years as in item 3, bl. 8)"
label  variable q86  "Whether any medical service provided free"
label  variable q87  "Surgery"
label  variable q88  "Medicine received (AYUSH)"
label  variable q89  "Medicine received other than AYUSH"
label  variable q810  "X-ray/ ECG/ EEG/ Scan"
label  variable q811  "Other diagnostic tests"
label  variable q812  "Doctor's/ surgeon's fee (Rs.)"
label  variable q813  "Medicines (Rs.): AYUSH"
label  variable q814  "Medicines (Rs.): Other than AYUSH"
label  variable q815  "Diagonistic tests (Rs.)"
label  variable q816  "Other medical expenses (Rs.)"
label  variable q817  "Medical expenditure(Rs.): total(items 10 to 14)"
label  variable q818  "Transport for patient (Rs.)"
label  variable q819  "Other expenses (Rs.)"
label  variable q820  "Expenditure (Rs.): Total (items 15 to 17)"
label  variable q825  "Blank"
label  variable nss  "NSS"
label  variable nsc  "NSC"
label  variable mlt  "MULT"

//Level 10

label  variable c1  "Centre, Round"
label  variable c2  "FSU Serial No."
label  variable c3  "Round"
label  variable c4  "Schedule"
label  variable c5  "Sample"
label  variable c6  "Sector"
label  variable c7  "NSS-Region"
label  variable c8  "District"
label  variable c9  "Stratum"
label  variable c10  "Sub-stratum"
label  variable c11  "Sub-Round"
label  variable c12  "Sub-sample"
label  variable c13  "FOD-Sub-Region"
label  variable c14  "Hamlet group/ Sub-block no."
label  variable c15  "Second-stage-stratum no."
label  variable c16  "Sample hhld. No."
label  variable q82a  "Level"
label  variable q83a  "Filler"
label  variable q84b  "Srl. no. of spell of ailment(as in item 1, block 8)"
label  variable q84c  "Srl. no. of member reporting ailment(as in item 2, block 8)"
label  variable q85a  "Age (in years as in item 3, bl. 8)"
label  variable q821  "Total amount reimbursed by medical insurance (Rs.)"
label  variable q822  "Major source of finance"
label  variable q824  "Place of treatment"
label  variable q824a  "If code 5 in item 21, state code"
label  variable q826  "Loss of household income, due to treatment(Rs.)"
label  variable q825a  "Blank"
label  variable nss  "NSS"
label  variable nsc   "NSC"
label  variable mlt  "MULT"


//Level 11

label  variable c1  "Centre, Round"
label  variable c2  "FSU Serial No."
label  variable c3  "Round"
label  variable c4  "Schedule"
label  variable c5  "Sample"
label  variable c6  "Sector"
label  variable c7  "NSS-Region"
label  variable c8  "District"
label  variable c9  "Stratum"
label  variable c10  "Sub-stratum"
label  variable c11  "Sub-Round"
label  variable c12  "Sub-sample"
label  variable c13  "FOD-Sub-Region"
label  variable c14  "Hamlet group/ Sub-block no."
label  variable c15  "Second-stage-stratum no."
label  variable c16  "Sample hhld. No."
label variable q92 "Level"
label variable q93 "Filler"
label variable q94 "Srl. no. of  member (as in col. 1, bl. 4A)"
label variable q95 "Age (as in col. 5, bl. 4A)"
label variable q96 "No. of sons living"
label variable q97 "No. of daughters living"
label variable q98 "State of economic independence"
label variable q99 "No. of dependents"
label variable q910 "Person financially supporting aged person"
label variable q910a "Place of stay"
label variable q911 "Living arrangement"
label variable q912 "Physical mobility"
label variable q913 "Person helping"
label variable q914 "Own perception-current state of health"
label variable q915 "Own perception- change in state of health"
label variable q916 "Blank"
label variable q917 "NSS"
label variable q918 "NSC"
label variable q919 "MULT"



//Level 12

label  variable c1  "Centre, Round"
label  variable c2  "FSU Serial No."
label  variable c3  "Round"
label  variable c4  "Schedule"
label  variable c5  "Sample"
label  variable c6  "Sector"
label  variable c7  "NSS-Region"
label  variable c8  "District"
label  variable c9  "Stratum"
label  variable c10  "Sub-stratum"
label  variable c11  "Sub-Round"
label  variable c12  "Sub-sample"
label  variable c13  "FOD-Sub-Region"
label  variable c14  "Hamlet group/ Sub-block no."
label  variable c15  "Second-stage-stratum no."
label  variable c16  "Sample hhld. No."
label  variable q122 "Level"
label  variable q123 "Filler"
label  variable q124 "Srl. no. of  member (as in col. 1, bl. 4)"
label  variable q125 "Age in months"
label  variable q126 "BCG"
label  variable q127 "oral Polio Vaccine doses : birth dose"
label  variable q128 "oral Polio Vaccine doses : OPV1"
label  variable q129 "oral Polio Vaccine doses : OPV2"
label  variable q1210 "oral Polio Vaccine doses : OPV3"
label  variable q1211 "oral Polio Vaccine doses : booster dose"
label  variable q1212 "DPT/Pentavalent doses: DPT-1/Pentavalent-1"
label  variable q1213 "DPT/Pentavalent doses: DPT-2/Pentavalent-2"
label  variable q1214 "DPT/Pentavalent doses: DPT-3/Pentavalent-3"
label  variable q1215 "DPT/Pentavalent doses: booster"
label  variable q1216 "Measles"
label  variable q1217 "Other immunisation"
label  variable q1218 "Information source of immunisation"
label  variable q1219 "Source of most immunisation"
label  variable q1220 "Expenditure on immunisation during last 365 days(Rs.)"
label  variable q1221 "Visit to anganwari centre during last 30 days(in days)"
label  variable q1222 "Blank"
label  variable q1223 "NSS"
label  variable q1224 "NSC"
label  variable q1225 "MULT"



//Level 13

label  variable c1  "Centre, Round"
label  variable c2  "FSU Serial No."
label  variable c3  "Round"
label  variable c4  "Schedule"
label  variable c5  "Sample"
label  variable c6  "Sector"
label  variable c7  "NSS-Region"
label  variable c8  "District"
label  variable c9  "Stratum"
label  variable c10  "Sub-stratum"
label  variable c11  "Sub-Round"
label  variable c12  "Sub-sample"
label  variable c13  "FOD-Sub-Region"
label  variable c14  "Hamlet group/ Sub-block no."
label  variable c15  "Second-stage-stratum no."
label  variable c16  "Sample hhld. No."
label  variable q102 "Level"
label  variable q103 "Filler"
label  variable q104 "Srl. no. of  member (as in bl. 4/ 5)"
label  variable q105 "Age (as in bl. 4/ 5)"
label  variable q107 "Srl. no. of pregnancy(1/2)"
label  variable q108 "Whether received tetanus toxoid vaccine during pregnancy"
label  variable q109 "Whether consumed Iron and Folic Acid(IFA) during pregnancy"
label  variable q109a "How many days IFA were consumed"
label  variable q1010 "Major source of receiving pre-natal care"
label  variable q1011 "Nature of pre-natal care"
label  variable q1011a "No. of pre-natal care visits"
label  variable q1012 "Total expenditure incurred on pre-natal care (Rs.)"
label  variable q1013 "Outcome of pregnancy"
label  variable q1014 "Place of delivery / abortion"
label  variable q1014a "Delivery was attended by"
label  variable q1014b "Expenditure of delivery at home(Rs.)"
label  variable q1015 "Major source of receiving post-natal care"
label  variable q1016 "Nature of post-natal care"
label  variable q1017 "Total expenditure incurred on post-natal care (Rs.)"
label  variable q1017a "Visit to anganwari centre(AWC) during last 30 days (in days)"
label  variable q1018 "Blank"
label  variable nss "NSS"
label  variable nsc "NSC"
label  variable mlt "MULT"


